version: "3"
services:
  gateway:
    build: ./service
    ports:
     - 5001:8080
  
  website:
    image: php:apache
    volumes:
     - ./website:/var/www/html
    ports:
     - 80:80
    depends_on:
     - gateway